### ISSUE TITLE
Pushr Daemon not starting with Rails 4.2.4

### ISSUE THREAD

**Issue by tilo** [9to5/pushr-core#15]
```
bundle exec pushr -f
/opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/core.rb:46:in `configurations=': uninitialized constant ActiveRecord::ConnectionHandling::MergeAndResolveDefaultUrlConfig (NameError)
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/core.rb:48:in `block in <module:Core>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `class_eval'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/concern.rb:120:in `append_features'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/base.rb:284:in `include'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/base.rb:284:in `<class:Base>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/base.rb:269:in `<module:ActiveRecord>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/base.rb:26:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:9:in `<class:PostgreSQLDatabaseTasks>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:5:in `<module:Tasks>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:4:in `<module:ActiveRecord>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:3:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/postgis_database_tasks.rb:4:in `<module:PostGIS>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/postgis_database_tasks.rb:3:in `<module:ConnectionAdapters>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/postgis_database_tasks.rb:2:in `<module:ActiveRecord>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis/postgis_database_tasks.rb:1:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis_adapter.rb:18:in `require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/active_record/connection_adapters/postgis_adapter.rb:18:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/activerecord-postgis-adapter.rb:1:in `require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-postgis-adapter-3.0.0/lib/activerecord-postgis-adapter.rb:1:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /opt/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/bin/pushr:4:in `<top (required)>'
	from /opt/rubies/ruby-2.2.0/bin/pushr:23:in `load'
	from /opt/rubies/ruby-2.2.0/bin/pushr:23:in `<main>'
```

**Comment by tilo** [comment]
something with the initialization is broken.. 

when I try to access ActiveRecord::ConnectionHandling::MergeAndResolveDefaultUrlConfig 
in the rails console, it's defined

**Comment by tompesman** [comment]
can you run something else? for example `bundle exec rake -T`

**Comment by tilo** [comment]
yes, anything else seems to work. Start-up is working in the rails console or server 
as well

**Comment by tilo** [comment]
when I'm in the console, ActiveRecord::ConnectionHandling::MergeAndResolveDefaultUrlConfig is available, but somehow it's not included at the proper moment during pushr daemon start-up

**Comment by tilo** [comment]
It's crashing with Rails 4.2.4

looks like it tries to establish the database connection as part of the rails initialization

pushr line 23:     load Gem.bin_path('pushr-core', 'pushr', version)

==> 

activerecord-4.2.4/lib/active_record/core.rb:46:in `configurations=': uninitialized constant ActiveRecord::ConnectionHandling::MergeAndResolveDefaultUrlConfig (NameError)

**Comment by tilo** [comment]
Looks like this only happens when I specify the postgres/postgis adapber in database.yml: 
    rgeo/activerecord-postgis-adapter

**Comment by tompesman** [comment]
Do you have a sample project so I can test it?

**Comment by tilo** [comment]
https://github.com/rgeo/activerecord-postgis-adapter/issues/201

**Comment by tompesman** [comment]
it's unrelated to pushr?

**Comment by s33m4nn** [comment]
I’m testing multiple certificates.
I’ve got bad password for one of the cert.

thx
Gabor
