### ISSUE TITLE
Problems when sending via APNS

### ISSUE THREAD

**Issue by tilo** [9to5/pushr-core#18]
```
[2016-03-25 18:02:31 +0000] ERROR: Errno::ECONNRESET, Connection reset by peer: /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/openssl/buffering.rb:61:in `sysread'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/openssl/buffering.rb:61:in `fill_rbuff'
/opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/openssl/buffering.rb:102:in `read'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-apns-1.0.1/lib/pushr/daemon/apns_support/connection_apns.rb:53:in `read'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-apns-1.0.1/lib/pushr/daemon/apns_support/connection_apns.rb:97:in `check_for_error'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-apns-1.0.1/lib/pushr/daemon/apns_support/connection_apns.rb:82:in `write'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/daemon/message_handler.rb:33:in `block in handle_next'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/core.rb:75:in `block in instrument'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/core.rb:74:in `instrument'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/daemon/message_handler.rb:32:in `handle_next'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/daemon/message_handler.rb:16:in `block (2 levels) in start'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/daemon/message_handler.rb:15:in `loop'
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/pushr-core-1.0.2/lib/pushr/daemon/message_handler.rb:15:in `block in start'
```

**Comment by tilo** [comment]
Ruby 2.2.3
Rails 4.2.4
pushr-apns 1.0.1

**Comment by tilo** [comment]
the feedback connection seems to work

**Comment by tompesman** [comment]
@tilo you provide the config excluding the certificate?
